### ISSUE TITLE
When using in robotframework the python stay zombie and it not finish the execution

### ISSUE THREAD

**Issue by TA-ELearning** [mihaiparvu/ScreenCapLibrary#67] opened 2021-01-13 14:36 UTC
General information:

* OS name: Windows
* OS version: 10
* OS architecture: 64 bits
* Python version: 3.9.0
* mss version: 4.0.3
* pygtk usage: no

### Description of the warning/error

Using the Library in robot tests
![image](https://user-images.githubusercontent.com/77101810/104463976-52fc4d80-55aa-11eb-8572-baa7c62de850.png)

Then running the robot framework command 

robot -d Results -v env:qa -i TC0001 Tests

the python stay zombie at the end 
![image](https://user-images.githubusercontent.com/77101810/104464178-8ccd5400-55aa-11eb-95c6-3ead728aff1f.png)

and in command line
![image](https://user-images.githubusercontent.com/77101810/104464596-07966f00-55ab-11eb-800f-ca74dd675bba.png)

and to release the python it is need to kill the interpreter
![image](https://user-images.githubusercontent.com/77101810/104464813-4298a280-55ab-11eb-8227-b56b8bdf3eea.png)

### Other details

More information

 robotframework-screencaplibrary in  (1.5.0)
 pillow>=5.2.0 in  (from robotframework-screencaplibrary) (8.1.0)
 opencv-python>=4.2.0.32 in  (from robotframework-screencaplibrary) (4.5.1.48)
 imageio>=2.6.1 in  (from robotframework-screencaplibrary) (2.9.0)
 mss>=4.0.3 in  (from robotframework-screencaplibrary) (6.1.0)
 robotframework>=3.0 in  (from robotframework-screencaplibrary) (3.2.2)
 pyautogui>=0.9.52 in  (from robotframework-screencaplibrary) (0.9.52)
 numpy in  (from imageio>=2.6.1->robotframework-screencaplibrary) (1.19.5)
 pymsgbox in  (from pyautogui>=0.9.52->robotframework-screencaplibrary) (1.0.9)
 PyTweening>=1.0.1 in  (from pyautogui>=0.9.52->robotframework-screencaplibrary) (1.0.3)
 pyscreeze>=0.1.21 in  (from pyautogui>=0.9.52->robotframework-screencaplibrary) (0.1.26)
 pygetwindow>=0.0.5 in  (from pyautogui>=0.9.52->robotframework-screencaplibrary) (0.0.9)
 mouseinfo in  (from pyautogui>=0.9.52->robotframework-screencaplibrary) (0.1.3)
 pyrect in  (from pygetwindow>=0.0.5->pyautogui>=0.9.52->robotframework-screencaplibrary) (0.1.4)
 pyperclip in  (from mouseinfo->pyautogui>=0.9.52->robotframework-screencaplibrary) (1.8.1)

**Comment by cristii006** [comment] 2021-01-27 12:44
Hello @TA-ELearning,

First thank you for detailed problem description and reproduction steps. Indeed this is a reproducible problem that occur only when using `Python 3.9`. I tried with other Python versions to recreate the problem and it is working fine. Other `robotframework` libraries are working as expected. After some testing we are clear now that the problem is occurring only when recording the screen because keywords like `Take Screenshot` are working fine. It seems like the way we handle the thread that is capturing the screen is causing this problem.

We will have to find a fix for this problem as the task is consuming resources until we end it.

Best regards, 
Cristi

**Comment by mihaiparvu** [comment] 2021-02-11 13:11
Fixed in https://github.com/mihaiparvu/ScreenCapLibrary/commit/ad865d90f7130b6dbd3506c5607873b70874b672

**Closed by mihaiparvu** 2021-02-11 13:11 UTC
